<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!--This file represents the results of running a test suite-->
<test-results name="C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\bin\Release\Resources.dll" total="18" errors="11" failures="4" not-run="0" inconclusive="0" ignored="0" skipped="0" invalid="0" date="2016-03-22" time="19:49:01">
  <environment nunit-version="2.6.3.13283" clr-version="2.0.50727.4927" os-version="Microsoft Windows NT 6.1.7600.0" platform="Win32NT" cwd="C:\Program Files (x86)\NUnit 2.6.3\bin" machine-name="MAXIMILIANOFELI" user="Maximiliano Felice" user-domain="MaximilianoFeli" />
  <culture-info current-culture="es-ES" current-uiculture="es-ES" />
  <test-suite type="Assembly" name="C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\bin\Release\Resources.dll" executed="True" result="Failure" success="False" time="5.181" asserts="0">
    <results>
      <test-suite type="Namespace" name="HotelModel" executed="True" result="Failure" success="False" time="5.129" asserts="0">
        <results>
          <test-suite type="Namespace" name="DB_Conn_DSL" executed="True" result="Failure" success="False" time="3.286" asserts="0">
            <results>
              <test-suite type="Namespace" name="tests" executed="True" result="Failure" success="False" time="3.285" asserts="0">
                <results>
                  <test-suite type="TestFixture" name="SqlQuery_tests" executed="True" result="Failure" success="False" time="2.547" asserts="0">
                    <results>
                      <test-case name="HotelModel.DB_Conn_DSL.tests.SqlQuery_tests.ExecutesValidQuery" executed="True" result="Error" success="False" time="2.501" asserts="0">
                        <failure>
                          <message><![CDATA[System.Data.SqlClient.SqlException : La conexión con el servidor se ha establecido correctamente, pero se ha producido un error durante el proceso de inicio de sesión. (provider: Proveedor de memoria compartida, error: 0 - No hay ningún proceso en el otro extremo de la canalización.)]]></message>
                          <stack-trace><![CDATA[en System.Data.ProviderBase.DbConnectionPool.GetConnection(DbConnection owningObject)
en System.Data.ProviderBase.DbConnectionFactory.GetConnection(DbConnection owningConnection)
en System.Data.ProviderBase.DbConnectionClosed.OpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory)
en System.Data.SqlClient.SqlConnection.Open()
en System.Data.Common.DbDataAdapter.QuietOpen(IDbConnection connection, ConnectionState& originalState)
en System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
en System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
en System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
en HotelModel.DB_Conn_DSL.DataSetRetriever.Execute(SqlCommand Command) en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\DB Conn DSL\DataSetRetriever.cs:línea 20
en HotelModel.DB_Conn_DSL.SqlCommandDSL.Execute() en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\DB Conn DSL\SqlCommandDSL.cs:línea 26
en HotelModel.DB_Conn_DSL.tests.SqlQuery_tests.ExecutesValidQuery() en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\DB Conn DSL\tests\SqlQuery_tests.cs:línea 21
]]></stack-trace>
                        </failure>
                      </test-case>
                    </results>
                  </test-suite>
                  <test-suite type="TestFixture" name="StoredProcedureConnection_tests" executed="True" result="Failure" success="False" time="0.448" asserts="0">
                    <results>
                      <test-case name="HotelModel.DB_Conn_DSL.tests.StoredProcedureConnection_tests.AddsNewProperties" executed="True" result="Success" success="True" time="0.123" asserts="3" />
                      <test-case name="HotelModel.DB_Conn_DSL.tests.StoredProcedureConnection_tests.CreatesNewSoredProcedure" executed="True" result="Success" success="True" time="0.003" asserts="2" />
                      <test-case name="HotelModel.DB_Conn_DSL.tests.StoredProcedureConnection_tests.ExecuteReturnsAllOutputParams" executed="True" result="Error" success="False" time="0.032" asserts="0">
                        <failure>
                          <message><![CDATA[System.Data.SqlClient.SqlException : La conexión con el servidor se ha establecido correctamente, pero se ha producido un error durante el proceso de inicio de sesión. (provider: Proveedor de memoria compartida, error: 0 - No hay ningún proceso en el otro extremo de la canalización.)]]></message>
                          <stack-trace><![CDATA[en System.Data.ProviderBase.DbConnectionPool.GetConnection(DbConnection owningObject)
en System.Data.ProviderBase.DbConnectionFactory.GetConnection(DbConnection owningConnection)
en System.Data.ProviderBase.DbConnectionClosed.OpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory)
en System.Data.SqlClient.SqlConnection.Open()
en System.Data.Common.DbDataAdapter.QuietOpen(IDbConnection connection, ConnectionState& originalState)
en System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
en System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
en System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
en HotelModel.DB_Conn_DSL.DataSetRetriever.Execute(SqlCommand Command) en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\DB Conn DSL\DataSetRetriever.cs:línea 20
en HotelModel.DB_Conn_DSL.SqlCommandDSL.Execute() en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\DB Conn DSL\SqlCommandDSL.cs:línea 26
en HotelModel.DB_Conn_DSL.tests.StoredProcedureConnection_tests.ExecuteReturnsAllOutputParams() en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\DB Conn DSL\tests\StoredProcedureConnection_tests.cs:línea 71
]]></stack-trace>
                        </failure>
                      </test-case>
                      <test-case name="HotelModel.DB_Conn_DSL.tests.StoredProcedureConnection_tests.ExecuteWithComeback" executed="True" result="Error" success="False" time="0.006" asserts="0">
                        <failure>
                          <message><![CDATA[System.Data.SqlClient.SqlException : La conexión con el servidor se ha establecido correctamente, pero se ha producido un error durante el proceso de inicio de sesión. (provider: Proveedor de memoria compartida, error: 0 - No hay ningún proceso en el otro extremo de la canalización.)]]></message>
                          <stack-trace><![CDATA[en System.Data.ProviderBase.DbConnectionPool.GetConnection(DbConnection owningObject)
en System.Data.ProviderBase.DbConnectionFactory.GetConnection(DbConnection owningConnection)
en System.Data.ProviderBase.DbConnectionClosed.OpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory)
en System.Data.SqlClient.SqlConnection.Open()
en System.Data.Common.DbDataAdapter.QuietOpen(IDbConnection connection, ConnectionState& originalState)
en System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
en System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
en System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
en HotelModel.DB_Conn_DSL.DataSetRetriever.Execute(SqlCommand Command) en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\DB Conn DSL\DataSetRetriever.cs:línea 20
en HotelModel.DB_Conn_DSL.SqlCommandDSL.Execute() en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\DB Conn DSL\SqlCommandDSL.cs:línea 26
en HotelModel.DB_Conn_DSL.tests.StoredProcedureConnection_tests.ExecuteWithComeback() en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\DB Conn DSL\tests\StoredProcedureConnection_tests.cs:línea 90
]]></stack-trace>
                        </failure>
                      </test-case>
                      <test-case name="HotelModel.DB_Conn_DSL.tests.StoredProcedureConnection_tests.HasNoComeback" executed="True" result="Failure" success="False" time="0.015" asserts="0">
                        <failure>
                          <message><![CDATA[An unexpected exception type was thrown
Expected: System.Collections.Generic.KeyNotFoundException
 but was: System.Data.SqlClient.SqlException : La conexión con el servidor se ha establecido correctamente, pero se ha producido un error durante el proceso de inicio de sesión. (provider: Proveedor de memoria compartida, error: 0 - No hay ningún proceso en el otro extremo de la canalización.)]]></message>
                          <stack-trace><![CDATA[en System.Data.ProviderBase.DbConnectionPool.GetConnection(DbConnection owningObject)
en System.Data.ProviderBase.DbConnectionFactory.GetConnection(DbConnection owningConnection)
en System.Data.ProviderBase.DbConnectionClosed.OpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory)
en System.Data.SqlClient.SqlConnection.Open()
en System.Data.Common.DbDataAdapter.QuietOpen(IDbConnection connection, ConnectionState& originalState)
en System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
en System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
en System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
en HotelModel.DB_Conn_DSL.DataSetRetriever.Execute(SqlCommand Command) en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\DB Conn DSL\DataSetRetriever.cs:línea 20
en HotelModel.DB_Conn_DSL.SqlCommandDSL.Execute() en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\DB Conn DSL\SqlCommandDSL.cs:línea 26
en HotelModel.DB_Conn_DSL.tests.StoredProcedureConnection_tests.HasNoComeback() en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\DB Conn DSL\tests\StoredProcedureConnection_tests.cs:línea 105
]]></stack-trace>
                        </failure>
                      </test-case>
                      <test-case name="HotelModel.DB_Conn_DSL.tests.StoredProcedureConnection_tests.RetunsValidDataReader" executed="True" result="Error" success="False" time="0.044" asserts="0">
                        <failure>
                          <message><![CDATA[System.InvalidOperationException : ExecuteReader requiere una conexión abierta y disponible. El estado actual de la conexión es cerrada.]]></message>
                          <stack-trace><![CDATA[en System.Data.SqlClient.SqlConnection.GetOpenConnection(String method)
en System.Data.SqlClient.SqlConnection.ValidateConnectionForExecute(String method, SqlCommand command)
en System.Data.SqlClient.SqlCommand.ValidateCommand(String method, Boolean async)
en System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, DbAsyncResult result)
en System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
en System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
en System.Data.SqlClient.SqlCommand.ExecuteReader()
en HotelModel.DB_Conn_DSL.DataReaderRetriever.Execute(SqlCommand Command) en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\DB Conn DSL\DataReaderRetriever.cs:línea 16
en HotelModel.DB_Conn_DSL.SqlCommandDSL.Execute() en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\DB Conn DSL\SqlCommandDSL.cs:línea 26
en HotelModel.DB_Conn_DSL.tests.StoredProcedureConnection_tests.RetunsValidDataReader() en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\DB Conn DSL\tests\StoredProcedureConnection_tests.cs:línea 115
]]></stack-trace>
                        </failure>
                      </test-case>
                      <test-case name="HotelModel.DB_Conn_DSL.tests.StoredProcedureConnection_tests.ReturnsValidDataTable" executed="True" result="Error" success="False" time="0.037" asserts="0">
                        <failure>
                          <message><![CDATA[System.InvalidOperationException : ExecuteReader requiere una conexión abierta y disponible. El estado actual de la conexión es cerrada.]]></message>
                          <stack-trace><![CDATA[en System.Data.SqlClient.SqlConnection.GetOpenConnection(String method)
en System.Data.SqlClient.SqlConnection.ValidateConnectionForExecute(String method, SqlCommand command)
en System.Data.SqlClient.SqlCommand.ValidateCommand(String method, Boolean async)
en System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, DbAsyncResult result)
en System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
en System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
en System.Data.SqlClient.SqlCommand.ExecuteReader()
en HotelModel.DB_Conn_DSL.DataTableRetriever.Execute(SqlCommand Command) en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\DB Conn DSL\DataTableRetriever.cs:línea 17
en HotelModel.DB_Conn_DSL.SqlCommandDSL.Execute() en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\DB Conn DSL\SqlCommandDSL.cs:línea 26
en HotelModel.DB_Conn_DSL.tests.StoredProcedureConnection_tests.ReturnsValidDataTable() en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\DB Conn DSL\tests\StoredProcedureConnection_tests.cs:línea 129
]]></stack-trace>
                        </failure>
                      </test-case>
                      <test-case name="HotelModel.DB_Conn_DSL.tests.StoredProcedureConnection_tests.ReturnValuesWorks" executed="True" result="Error" success="False" time="0.006" asserts="0">
                        <failure>
                          <message><![CDATA[System.Data.SqlClient.SqlException : La conexión con el servidor se ha establecido correctamente, pero se ha producido un error durante el proceso de inicio de sesión. (provider: Proveedor de memoria compartida, error: 0 - No hay ningún proceso en el otro extremo de la canalización.)]]></message>
                          <stack-trace><![CDATA[en System.Data.ProviderBase.DbConnectionPool.GetConnection(DbConnection owningObject)
en System.Data.ProviderBase.DbConnectionFactory.GetConnection(DbConnection owningConnection)
en System.Data.ProviderBase.DbConnectionClosed.OpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory)
en System.Data.SqlClient.SqlConnection.Open()
en System.Data.Common.DbDataAdapter.QuietOpen(IDbConnection connection, ConnectionState& originalState)
en System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
en System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
en System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
en HotelModel.DB_Conn_DSL.DataSetRetriever.Execute(SqlCommand Command) en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\DB Conn DSL\DataSetRetriever.cs:línea 20
en HotelModel.DB_Conn_DSL.SqlCommandDSL.Execute() en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\DB Conn DSL\SqlCommandDSL.cs:línea 26
en HotelModel.DB_Conn_DSL.tests.StoredProcedureConnection_tests.ReturnValuesWorks() en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\DB Conn DSL\tests\StoredProcedureConnection_tests.cs:línea 141
]]></stack-trace>
                        </failure>
                      </test-case>
                      <test-case name="HotelModel.DB_Conn_DSL.tests.StoredProcedureConnection_tests.userLoginIsCorrect" executed="True" result="Error" success="False" time="0.008" asserts="0">
                        <failure>
                          <message><![CDATA[System.Data.SqlClient.SqlException : La conexión con el servidor se ha establecido correctamente, pero se ha producido un error durante el proceso de inicio de sesión. (provider: Proveedor de memoria compartida, error: 0 - No hay ningún proceso en el otro extremo de la canalización.)]]></message>
                          <stack-trace><![CDATA[en System.Data.ProviderBase.DbConnectionPool.GetConnection(DbConnection owningObject)
en System.Data.ProviderBase.DbConnectionFactory.GetConnection(DbConnection owningConnection)
en System.Data.ProviderBase.DbConnectionClosed.OpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory)
en System.Data.SqlClient.SqlConnection.Open()
en System.Data.Common.DbDataAdapter.QuietOpen(IDbConnection connection, ConnectionState& originalState)
en System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
en System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
en System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
en HotelModel.DB_Conn_DSL.DataSetRetriever.Execute(SqlCommand Command) en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\DB Conn DSL\DataSetRetriever.cs:línea 20
en HotelModel.DB_Conn_DSL.SqlCommandDSL.Execute() en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\DB Conn DSL\SqlCommandDSL.cs:línea 26
en HotelModel.DB_Conn_DSL.tests.StoredProcedureConnection_tests.userLoginIsCorrect() en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\DB Conn DSL\tests\StoredProcedureConnection_tests.cs:línea 53
]]></stack-trace>
                        </failure>
                      </test-case>
                      <test-case name="HotelModel.DB_Conn_DSL.tests.StoredProcedureConnection_tests.userLoginIsNotCorrect" executed="True" result="Error" success="False" time="0.006" asserts="0">
                        <failure>
                          <message><![CDATA[System.Data.SqlClient.SqlException : La conexión con el servidor se ha establecido correctamente, pero se ha producido un error durante el proceso de inicio de sesión. (provider: Proveedor de memoria compartida, error: 0 - No hay ningún proceso en el otro extremo de la canalización.)]]></message>
                          <stack-trace><![CDATA[en System.Data.ProviderBase.DbConnectionPool.GetConnection(DbConnection owningObject)
en System.Data.ProviderBase.DbConnectionFactory.GetConnection(DbConnection owningConnection)
en System.Data.ProviderBase.DbConnectionClosed.OpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory)
en System.Data.SqlClient.SqlConnection.Open()
en System.Data.Common.DbDataAdapter.QuietOpen(IDbConnection connection, ConnectionState& originalState)
en System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
en System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
en System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
en HotelModel.DB_Conn_DSL.DataSetRetriever.Execute(SqlCommand Command) en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\DB Conn DSL\DataSetRetriever.cs:línea 20
en HotelModel.DB_Conn_DSL.SqlCommandDSL.Execute() en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\DB Conn DSL\SqlCommandDSL.cs:línea 26
en HotelModel.DB_Conn_DSL.tests.StoredProcedureConnection_tests.userLoginIsNotCorrect() en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\DB Conn DSL\tests\StoredProcedureConnection_tests.cs:línea 65
]]></stack-trace>
                        </failure>
                      </test-case>
                    </results>
                  </test-suite>
                </results>
              </test-suite>
            </results>
          </test-suite>
          <test-suite type="Namespace" name="User_Permissions" executed="True" result="Failure" success="False" time="1.800" asserts="0">
            <results>
              <test-suite type="Namespace" name="tests" executed="True" result="Failure" success="False" time="1.799" asserts="0">
                <results>
                  <test-suite type="TestFixture" name="Annotated_Forms_Tests" executed="True" result="Failure" success="False" time="1.659" asserts="0">
                    <results>
                      <test-case name="HotelModel.User_Permissions.tests.Annotated_Forms_Tests.Check_Instance_Class" executed="True" result="Error" success="False" time="1.632" asserts="0">
                        <failure>
                          <message><![CDATA[SetUp : System.Data.SqlClient.SqlException : La conexión con el servidor se ha establecido correctamente, pero se ha producido un error durante el proceso de inicio de sesión. (provider: Proveedor de memoria compartida, error: 0 - No hay ningún proceso en el otro extremo de la canalización.)]]></message>
                          <stack-trace><![CDATA[en System.Data.ProviderBase.DbConnectionPool.GetConnection(DbConnection owningObject)
en System.Data.ProviderBase.DbConnectionFactory.GetConnection(DbConnection owningConnection)
en System.Data.ProviderBase.DbConnectionClosed.OpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory)
en System.Data.SqlClient.SqlConnection.Open()
en System.Data.Common.DbDataAdapter.QuietOpen(IDbConnection connection, ConnectionState& originalState)
en System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
en System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
en System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
en HotelModel.DB_Conn_DSL.DataSetRetriever.Execute(SqlCommand Command) en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\DB Conn DSL\DataSetRetriever.cs:línea 20
en HotelModel.DB_Conn_DSL.SqlCommandDSL.Execute() en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\DB Conn DSL\SqlCommandDSL.cs:línea 26
en HotelModel.User_Permissions.UFR.Feature.LoadFeatures() en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\User Permissions\UFR\Feature.cs:línea 102
en HotelModel.User_Permissions.PermissionManager.StartPoint(Control BaseForm) en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\User Permissions\PermissionManager.cs:línea 190
]]></stack-trace>
                        </failure>
                      </test-case>
                      <test-case name="HotelModel.User_Permissions.tests.Annotated_Forms_Tests.GetHandledControls" executed="True" result="Error" success="False" time="0.003" asserts="0">
                        <failure>
                          <message><![CDATA[SetUp : System.Data.SqlClient.SqlException : La conexión con el servidor se ha establecido correctamente, pero se ha producido un error durante el proceso de inicio de sesión. (provider: Proveedor de memoria compartida, error: 0 - No hay ningún proceso en el otro extremo de la canalización.)]]></message>
                          <stack-trace><![CDATA[en System.Data.ProviderBase.DbConnectionPool.GetConnection(DbConnection owningObject)
en System.Data.ProviderBase.DbConnectionFactory.GetConnection(DbConnection owningConnection)
en System.Data.ProviderBase.DbConnectionClosed.OpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory)
en System.Data.SqlClient.SqlConnection.Open()
en System.Data.Common.DbDataAdapter.QuietOpen(IDbConnection connection, ConnectionState& originalState)
en System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
en System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
en System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
en HotelModel.DB_Conn_DSL.DataSetRetriever.Execute(SqlCommand Command) en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\DB Conn DSL\DataSetRetriever.cs:línea 20
en HotelModel.DB_Conn_DSL.SqlCommandDSL.Execute() en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\DB Conn DSL\SqlCommandDSL.cs:línea 26
en HotelModel.User_Permissions.UFR.Feature.LoadFeatures() en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\User Permissions\UFR\Feature.cs:línea 102
en HotelModel.User_Permissions.PermissionManager.StartPoint(Control BaseForm) en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\User Permissions\PermissionManager.cs:línea 190
]]></stack-trace>
                        </failure>
                      </test-case>
                    </results>
                  </test-suite>
                  <test-suite type="TestFixture" name="Features_test" executed="True" result="Failure" success="False" time="0.011" asserts="0">
                    <results>
                      <test-case name="HotelModel.User_Permissions.tests.Features_test.LoadFeatures" executed="True" result="Error" success="False" time="0.008" asserts="0">
                        <failure>
                          <message><![CDATA[System.Data.SqlClient.SqlException : La conexión con el servidor se ha establecido correctamente, pero se ha producido un error durante el proceso de inicio de sesión. (provider: Proveedor de memoria compartida, error: 0 - No hay ningún proceso en el otro extremo de la canalización.)]]></message>
                          <stack-trace><![CDATA[en System.Data.ProviderBase.DbConnectionPool.GetConnection(DbConnection owningObject)
en System.Data.ProviderBase.DbConnectionFactory.GetConnection(DbConnection owningConnection)
en System.Data.ProviderBase.DbConnectionClosed.OpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory)
en System.Data.SqlClient.SqlConnection.Open()
en System.Data.Common.DbDataAdapter.QuietOpen(IDbConnection connection, ConnectionState& originalState)
en System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
en System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
en System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
en HotelModel.DB_Conn_DSL.DataSetRetriever.Execute(SqlCommand Command) en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\DB Conn DSL\DataSetRetriever.cs:línea 20
en HotelModel.DB_Conn_DSL.SqlCommandDSL.Execute() en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\DB Conn DSL\SqlCommandDSL.cs:línea 26
en HotelModel.User_Permissions.UFR.Feature.LoadFeatures() en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\User Permissions\UFR\Feature.cs:línea 102
en HotelModel.User_Permissions.tests.Features_test.LoadFeatures() en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\User Permissions\tests\Features_test.cs:línea 16
]]></stack-trace>
                        </failure>
                      </test-case>
                    </results>
                  </test-suite>
                  <test-suite type="TestFixture" name="Hooks_tests" executed="True" result="Error" success="False" time="0.045" asserts="0">
                    <failure>
                      <message><![CDATA[SetUp : System.Data.SqlClient.SqlException : La conexión con el servidor se ha establecido correctamente, pero se ha producido un error durante el proceso de inicio de sesión. (provider: Proveedor de memoria compartida, error: 0 - No hay ningún proceso en el otro extremo de la canalización.)]]></message>
                      <stack-trace><![CDATA[en System.Data.ProviderBase.DbConnectionPool.GetConnection(DbConnection owningObject)
en System.Data.ProviderBase.DbConnectionFactory.GetConnection(DbConnection owningConnection)
en System.Data.ProviderBase.DbConnectionClosed.OpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory)
en System.Data.SqlClient.SqlConnection.Open()
en System.Data.Common.DbDataAdapter.QuietOpen(IDbConnection connection, ConnectionState& originalState)
en System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
en System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
en System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
en HotelModel.DB_Conn_DSL.DataSetRetriever.Execute(SqlCommand Command) en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\DB Conn DSL\DataSetRetriever.cs:línea 20
en HotelModel.DB_Conn_DSL.SqlCommandDSL.Execute() en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\DB Conn DSL\SqlCommandDSL.cs:línea 26
en HotelModel.User_Permissions.UFR.Feature.LoadFeatures() en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\User Permissions\UFR\Feature.cs:línea 102
en HotelModel.User_Permissions.tests.Hooks_tests.Init() en C:\Users\Maximiliano Felice\workspace\GDD\src\Resources\User Permissions\tests\Hooks_tests.cs:línea 22
]]></stack-trace>
                    </failure>
                    <results>
                      <test-case name="HotelModel.User_Permissions.tests.Hooks_tests.controlCanHandleVisibility" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Hooks_tests]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="HotelModel.User_Permissions.tests.Hooks_tests.controlGetsHooked" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Hooks_tests]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="HotelModel.User_Permissions.tests.Hooks_tests.HasFeaturesUP" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Hooks_tests]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                    </results>
                  </test-suite>
                  <test-suite type="TestFixture" name="Roles_tests" executed="True" result="Success" success="True" time="0.005" asserts="0">
                    <results>
                      <test-case name="HotelModel.User_Permissions.tests.Roles_tests.HasRolesUP" executed="True" result="Success" success="True" time="0.001" asserts="0" />
                    </results>
                  </test-suite>
                </results>
              </test-suite>
            </results>
          </test-suite>
        </results>
      </test-suite>
    </results>
  </test-suite>
</test-results>